### ISSUE TITLE
inst? coerce seems very strict

### ISSUE THREAD

**Issue by seancorfield** [wilkerlucio/spec-coerce#10]
We currently use conformers to provide API -> data coercion as part of a `::date` spec and we accept several string formats:
```
           ["yyyy/M/d" "M/d/yyyy"
            "yyyy-M-d" "M-d-yyyy"
            "EEE MMM dd HH:mm:ss zzz yyyy"]
```
I was hoping that `(sc/coerce `inst? input)` would be equally forgiving :) I was a bit surprised that even `"2018-7-23"` wasn't accepted (needs to be `"2018-07-23"`).

I know I could write a custom coercion but I wondered whether you've considered supporting more input formats for date coercion?

**Comment by wilkerlucio** [comment]
I would be pleased to accept a contribution to make it more permissive, the implementation is just the simplest I could do by the time.

**Comment by seancorfield** [comment]
Cool. I'll try to take a look and submit a PR later this week.

**Comment by seancorfield** [comment]
What is the minimum version of Java you support? If it's Java 8, I could use Java Time to try parsing several date/time formats (this is essentially what we do with our coercion at work -- we leverage `clojure.java-time` but it should be straightforward to use Java Time directly).

**Comment by seancorfield** [comment]
I'll also have to look at what works in JavaScript here (I'm not sure what types of string `js/Date.` accepts?).

**Comment by wilkerlucio** [comment]
> What is the minimum version of Java you support? If it's Java 8, I could use Java Time to try parsing several date/time formats (this is essentially what we do with our coercion at work -- we leverage `clojure.java-time` but it should be straightforward to use Java Time directly).

I think Java 8 is fine, nice to hear the js Date is already doing a good thing there.

**Comment by seancorfield** [comment]
Here's where I'm going with this https://github.com/seancorfield/spec-coerce/commit/46592d97260d75596dbd1d1be9d883d391b6fa8a

**Comment by wilkerlucio** [comment]
Closed by #11

**Comment by seancorfield** [comment]
What about running the CLJS tests?

**Comment by wilkerlucio** [comment]
Sorry, the cljs tests seem to be broken, I'll keep an issue to remember to fix, a port to shadow + karma will be better.

**Comment by seancorfield** [comment]
Cool. It looked like only _one_ test was broken. I wondered if maybe the newer version of ClojureScript that I bumped the dependencies too, in order to get `##Inf` etc to read, might also obviate the need for the `NaN` workarounds? I didn't actually try that tho'.
