### ISSUE TITLE
coerce! attempts to call s/valid? on unqualified keywords

### ISSUE THREAD

**Issue by stathissideris** [wilkerlucio/spec-coerce#14]
I tried to call `(sc/coerce-structure m {::sc/op sc/coerce!})` but it gives me exceptions for keys in my map that don't have a namespace. I think, for consistency with spec's behaviour, it should instead skip those keywords.

**Comment by stathissideris** [comment]
Maybe something like:

```clojure
(defn coerce!
  "Like coerce, but will call s/assert on the result, making it throw an error if value
  doesn't comply after coercion."
  [k x]
  (let [coerced (coerce k x)]
    (cond (simple-keyword? k)
          coerced
          (s/valid? k coerced)
          coerced
          :else
          (throw (ex-info "Failed to coerce value" {:spec  k
                                                    :value x})))))
```

**Comment by wilkerlucio** [comment]
@stathissideris thanks, that sounds a reasanable behavior, I just released `1.0.0-alpha8` using a more tolerant behavior for `coerce!` so it will not throw on simple keywords.

Closed by ab2867c5ff294854b02adb41fd8611f69f0604a4

**Comment by stathissideris** [comment]
Many thanks for doing this and for your prompt response! I and my colleagues are using spec-coerce in a couple of projects and we're finding very useful!

**Comment by wilkerlucio** [comment]
Nice, glad to hear that. :)
