### ISSUE TITLE
Coercion for Decimal doesn't work as expected

### ISSUE THREAD

**Issue by LukasRychtecky** [wilkerlucio/spec-coerce#15]
Hi,
thank you for this library.

When I get a number from e.g. Ring request I'd like to coerce it to Big Decimal.

```clojure
(s/def ::amount (s/and decimal? pos?))
(sc/coerce ::amount "") ;; throws java.lang.ArrayIndexOutOfBoundsException
;; but I expect to get "", because the value is not possible to coerce

(sc/coerce ::amount 1) ;; it returns 1
;; but I expect to get 1M, because the value is Long 
```

So I suggest to:
1. `parse-decimal` function should not care if `x` is `string` or not.
2. `parse-decimal` should be wrapped in `try-catch`.

What do you think about it?

**Comment by wilkerlucio** [comment]
hello @LukasRychtecky :)

I think it makes sense, can you like to send a PR with the described changes?
