### ISSUE TITLE
Coercion to string has no effect

### ISSUE THREAD

**Issue by nogden** [wilkerlucio/spec-coerce#17]
If a predicate `string?` is used for a spec, `coerce` does not coerce to a string.

```clojure
(s/def ::foo string?)
(sc/coerce ::foo 1)  ;=> 1
```

**Comment by wilkerlucio** [comment]
Thanks, that's an interesting case, when I designed the API the intent was to only coerce from string values, giving those are the ones "unencoded" in the message, usually when something is in other format is expected to be the correct one already. Is this a real use case or you just trying it around?

**Comment by nogden** [comment]
That makes sense. In this case I just came across this discrepancy whilst evaluating the library and thought it an odd case to be missing since for almost anything Clojure makes it easy to obtain a string representation. In terms of a real world use case, I admit, I'm struggling to think of one.

Feel free to close this if you think the benefit of consistency isn't worth effort needed to implement the conversion. Otherwise, I'll have a look at this later and it's a small amount of work, I'll submit a PR. Thanks for your time.

**Comment by wilkerlucio** [comment]
Ok, closing for now.
