### ISSUE TITLE
Throws error for a spec with an `or` form in the `:req-un` set of a `keys` form.

### ISSUE THREAD

**Issue by nogden** [wilkerlucio/spec-coerce#18]
In spec it is perfectly valid to logically or keys in the `:req(-un)` section of a `keys` form. E.g.
```clojure
;; A map that must have either a bar or a baz
(s/def ::foo (s/keys :req [(or ::bar ::baz)]))
```
Coerce throws an error when trying to coerce using a spec that uses `or` in the `:req-un` section of a `keys` form. E.g.
```clojure
(spec/def ::foo int?)
(spec/def ::bar string?)
(spec/def ::baz (spec/keys :req-un [(or ::foo ::bar)]))

(coerce/coerce ::baz {:foo "1" :bar "hi"}) ;=> ClassCastException
```
The same example using fully qualified keys (`:req`) seems to work correctly.

**Comment by wilkerlucio** [comment]
Nice catch, agreed its an inconsistency, I won't have time to work on this soon, but I'll be happy to merge a PR fixing it.

**Comment by nogden** [comment]
I'll take a look later this week or next week if I get a chance and hopefully put together a PR.
