### ISSUE TITLE
Bad coercions for pos/neg/nat specs

### ISSUE THREAD

**Issue by vemv** [wilkerlucio/spec-coerce#21]
`"-42"` coerced to pos?, pos-int?, nat?, nat-int? appears to result in `-42`.

Conversely, `"42"` coerced to `neg?`, `neg-int?` results in `42`.

The problem with this is that it's inconsistent with the general behavior that if x was coerced to pred, then f is a valid pred.

You can reproduce this adding some test cases:

![image](https://user-images.githubusercontent.com/1162994/56105364-22eacb00-5f3c-11e9-8459-bd545ce11e24.png)

Those cases will fail, and IMO they shouldn't.

WDYT?

Thanks - Victor

**Comment by wilkerlucio** [comment]
Yes, coercion tries to do it's best to convert the value into the right type (`pos-int?`, `nat-int?` and `neg-int?` are all variations of `int`, but they still ints), so this is the expected behavior if you want to validate you should use `s/valid?` on the coerced value. Makes sense?

**Comment by vemv** [comment]
Hey there,

> (pos-int?, nat-int? and neg-int? are all variations of int, but they still ints)

This has room for subjectivity of course. Probably you can also imagine how a half-coerced value might be problematic, bringing more confusion than convenience.

One also can imagine a more complex example of how a "half coercion" would yield a non-sensical value. Think nested data structures: would I like to debug on production why an intrincate piece of data has a totally unexpected shape?

> so this is the expected behavior if you want to validate you should use s/valid? on the coerced value.

Fortunately I'm doing this already, but perhaps you can leverage the fact that this `pos-int?`/etc behavior isn't particularly unit-tested, and therefore is undefined behavior. So it wouldn't be much of a breaking change.

It would simplify the code one has to write and also be consistent (I think) with other spec-coerce behavior.

**Comment by wilkerlucio** [comment]
Hello, I understand what you are saying, that's a valid way to think about it, but not the properties I'm looking for in this lib. I think coercion and validation are two separated things, this library tries to focus on coercion, validation is not really a concern. As you are already doing, you can validate later, if I change this lib to also validate, two things will happen:

1. break the code for people relying just on the coercion side (I have code myself doing that)
2. forces everybody that uses this library to pay the validation cost, even if they don't need it

Considering these I'm not convinced to change the behavior, its easy enough to write wrappers around the functions to get the validation, but once in the library, they couldn't be separated, so I prefer to don't complect things.

I'm closing for now, but feel free to keep the discussion if you have more points. Thanks.

**Comment by vemv** [comment]
I also can see how your stance is perfectly reasonable.

Happy to have at least tried!
