### ISSUE TITLE
Coercing a sequence changes its order

### ISSUE THREAD

**Issue by LukasRychtecky** [wilkerlucio/spec-coerce#22]
Hi,

when coercing a sequence its order is changed depending by its type (list/vector).

```clojure
(require '[clojure.spec.alpha :as s])
(require '[spec-coerce.core :as sc])

(s/def ::num int?)
(s/def ::obj (s/keys :req-un [::num]))
(s/def ::seq (s/coll-of ::obj))

(sc/coerce ::seq [{:a 1} {:a 2}]) ;; => [{:a 1} {:a 2}]
(sc/coerce ::seq (list {:a 1} {:a 2})) ;; => ({:a 2} {:a 1})
```

The reason is that `into` uses `(reduce conj ...` https://github.com/wilkerlucio/spec-coerce/blob/master/src/spec_coerce/core.cljc#L150

I'd fix it with something like this:
```clojure
(defn- map-seq
  [fun x]
  (if (vector? x)
    (mapv fun x)
    (map fun x)))

(defn parse-coll-of [[_ pred & _]]
  (fn [x]
    (if (sequential? x)
      (map-seq (partial coerce pred) x)
      x)))
```

What do you think?

**Comment by wilkerlucio** [comment]
Thanks for the report!

Fixed in https://github.com/wilkerlucio/spec-coerce/commit/20ae55b731387c0c6ba0ab13f12c2b7ff67f2f44

Fix release in version `1.0.0-alpha12`
