### ISSUE TITLE
Support for multi-specs?

### ISSUE THREAD

**Issue by Astronought** [wilkerlucio/spec-coerce#27]
Perhaps I'm missing something, but it seems from my experimentation that this library doesn't support coercion of multi-specs.

For example given a multi-spec such as:

`(spec/def ::event (spec/multi-spec event ::type)`

It'd be really awesome if I could do the following:

`(sc/coerce ::event {:type :some-event-type
                               :some-attribute-to-be-coerced "123"}`

and have the event data be coerced based on the multi-methods I have defined for the multi-spec.

Is there anything that prevents this or would it be possible to implement?

**Comment by wilkerlucio** [comment]
Fixed in `alpha-15`
