### ISSUE TITLE
Regex cat spec doesn't seem to be coerced at all

### ISSUE THREAD

**Issue by TuggyNE** [wilkerlucio/spec-coerce#40]
Suppose I have a spec registry like this:
```clojure
(s/def ::arg (s/or :int int? :boolean boolean? :keyword keyword? :string string?))
(s/def ::evt-kw keyword?)
(s/def ::arg-list (s/cat :evt-kw ::evt-kw :evt-args (s/* ::arg)))
```
Then `(sc/coerce ::evt-kw ":test")` returns `:test` (a keyword) as expected, but `(sc/coerce ::arg-list [":test"])` returns a vector with a string in it, `coerce!` throws, and `conform` returns `::s/invalid`. Is there any way to make use of the spec regex ops?

**Comment by wilkerlucio** [comment]
Currently, regexes specs are not supported.

As an alternative, you can use the custom coerce registry to make specific coercion for the `::arg-list` spec, like:

```clojure
(sc/def ::arg-list (fn your-coerce-impl [x] ...))
```

I think they could be implemented, but not a priority for me at the moment, but happy to receive contributions adding it :)

**Comment by TuggyNE** [comment]
All right, thank you for the quick response. It will be a lot quicker for now to define a custom coercion, but maybe later I or someone can write the regex support.

**Comment by wilkerlucio** [comment]
Cool, gonna close it, for now, we can reopen it if you or anyone else gets the time to work on it.
